services:
  - type: web
    name: geoaurora-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: REDIS_URL
        sync: false
      - key: NASA_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false

